development:
  adapter: postgresql
  database: fcards_development

test:
  adapter: postgresql
  database: fcards_test
#
production:
  adapter: postgresql
  database: fcards_production
  username: fcards
  password: <%= ENV['FCARDS_DATABASE_PASSWORD'] %>
